[custom]

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持
;显示IP归属地应用伪装：支持

;设置规则标志位

;跳过IP-ASN
rule_skip=IP-ASN

# 白名单
ruleset=🇨🇳 国内流量,clash-classic:https://raw.githubusercontent.com/LK373391947/Clash-/master/Clash/DIRECT_rule.yaml,no-resolve
# 本地规则
# ruleset=🇨🇳 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml,no-resolve
# 国内流量
ruleset=🇨🇳 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml,no-resolve
ruleset=🇨🇳 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml
ruleset=🇨🇳 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml
ruleset=🇨🇳 国内流量,clash-classic:https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/direct.list
# 日本专线
ruleset=🇯🇵 日本节点,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DMM/DMM.yaml
# Google规则
ruleset=🌐 Google,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
# 群晖规则
ruleset=🖥️ 群晖NAS,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Synology/Synology.yaml
# GitHub
# ruleset=🔗 GitHub,clash-classic:
# pikpak
ruleset=☁ pikpak,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.yaml
# Speedtest规则
ruleset=⏲ Speedtest,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
# OpenAI规则
ruleset=💬 OpenAi,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
# Netflix规则
ruleset=🎥 Netflix,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
# Disney规则
ruleset=🐹 Disney,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
# HBO规则
ruleset=🎦 HBO,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOHK/HBOHK.yaml
ruleset=🎦 HBO,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOAsia/HBOAsia.yaml
ruleset=🎦 HBO,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.yaml
# TikTok规则
ruleset=🎶 TikTok,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
# Spotify规则
ruleset=🎵 Spotify,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
# YouTube规则
ruleset=📹 YouTube,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
# Telegram规则
ruleset=📲 Telegram,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
# Paypal规则
ruleset=💰 PayPal,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml
# Microsoft规则
ruleset=Ⓜ️ 微软服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
# Twitter规则
ruleset=🕊 Twitter,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml
# Facebook
ruleset=📖 Facebook,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml
# Apple规则
ruleset=🍎 苹果服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml

# GlobalMedia规则
ruleset=🌍 国外媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml

# 自定义代理名单
ruleset=👈 自定义代理,clash-classic:https://raw.githubusercontent.com/LK373391947/Clash-/master/Clash/PROXY_rule.yaml,no-resolve

# Global规则
ruleset=🎯 国外流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml
ruleset=🎯 国外流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical.yaml


# Advertising规则
ruleset=🛑 广告拦截,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml

# 结束
# ruleset=🇨🇳 国内流量,[]GEOIP,CN,no-resolve

ruleset=🇨🇳 国内流量,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

# no-resolve	告诉 Clash 不进行 DNS 反向解析，提高效率，通常用于 IP-CIDR 等规则，避免解析延迟或出错（不是必须，但推荐加）
;设置规则标志位 

;设置分组标志位
custom_proxy_group=👈 自定义代理`select`[]DIRECT`.*
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]👈 自定义代理`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点
custom_proxy_group=🇨🇳 国内流量`select`[]DIRECT
custom_proxy_group=🎯 国外流量`select`[]♻️ 自动选择`[]DIRECT`.*
# custom_proxy_group=☀ 日本专线`select`[]🇯🇵 日本节点
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT`[]♻️ 自动选择
custom_proxy_group=⏲ Speedtest`select`[]DIRECT`.*
custom_proxy_group=🖥️ 群晖NAS`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=☁ pikpak`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🌐 Google`select`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=💰 PayPal`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🕊 Twitter`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=📖 Facebook`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=📲 Telegram`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=💬 OpenAi`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点
# custom_proxy_group=💬 OpenAi`url-test`(OpenAI|ChatGPT|解锁)`https://chat.openai.com/backend-api/models`500,100


custom_proxy_group=📹 YouTube`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🎥 Netflix`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🐹 Disney`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🎦 HBO`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🎵 Spotify`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🎶 TikTok`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🌍 国外媒体`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点

custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]♻️ 自动选择`[]🔓 解锁节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇹🇭 泰国节点`[]🇻🇳 越南节点`[]🇮🇩 印尼节点`[]🇲🇾 马来西亚节点`[]🇰🇭 柬埔寨节点`[]🇵🇭 菲律宾节点`[]🇦🇷 阿根廷节点`[]🇷🇺 俄罗斯节点`[]🇫🇷 法国节点`[]🇹🇷 土耳其节点`[]🇮🇹 意大利节点`[]🇩🇪 德国节点`[]🇸🇦 沙特节点`[]🇧🇷 巴西节点`[]🇳🇬 尼日利亚节点`[]🇲🇴 澳门节点



custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`(^(?!.*(电信|联通|移动)).*)`http://www.gstatic.com/generate_204`300,50
# custom_proxy_group=🔯 故障转移`fallback`(^(?!.*(电信|联通|移动)).*)`http://www.gstatic.com/generate_204`300,50
# custom_proxy_group=📶 官方优选`load-balance`(官方|防|电信|联通|移动|CT|CU|CM|CF|t.me|WARP|Warp|warp)`http://www.gstatic.com/generate_204`300,50

custom_proxy_group=🔓 解锁节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,150
custom_proxy_group=🇹🇼 台湾节点`url-test`(台湾|台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩国|韩|韓)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇬🇧 英国节点`url-test`(🇬🇧|伦敦|英国|GB|英|UK|England)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇦🇺 澳大利亚节点`url-test`(澳大利亚|澳洲|AU|Australia)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇨🇦 加拿大节点`url-test`(加拿大|CA|Canada)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇹🇭 泰国节点`url-test`(泰国|TH|Thailand)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇻🇳 越南节点`url-test`(越南|VN|Vietnam)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇮🇩 印尼节点`url-test`(印尼|ID|Indonesia)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇲🇾 马来西亚节点`url-test`(马来西亚|MY|Malaysia)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇰🇭 柬埔寨节点`url-test`(柬埔寨|KH|Cambodia)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇵🇭 菲律宾节点`url-test`(菲律宾|PH|Philippines)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇮🇳 印度节点`url-test`(印度|IN|India)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇦🇷 阿根廷节点`url-test`(阿根廷|AR|Argentina)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇷🇺 俄罗斯节点`url-test`(俄罗斯|RU|Russia)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇫🇷 法国节点`url-test`(法国|FR|France)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇹🇷 土耳其节点`url-test`(土耳其|TR|Turkey)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇮🇹 意大利节点`url-test`(意大利|IT|Italy)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇩🇪 德国节点`url-test`(德国|DE|Germany)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇸🇦 沙特节点`url-test`(沙特|SA|Saudi Arabia)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇧🇷 巴西节点`url-test`(巴西|BR|Brazil)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇳🇬 尼日利亚节点`url-test`(尼日利亚|NG|Nigeria)`http://www.gstatic.com/generate_204`300,50
custom_proxy_group=🇲🇴 澳门节点`url-test`(澳门|MO|Macau)`http://www.gstatic.com/generate_204`300,50




;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/cutethotw/ClashRule/main/GeneralClashConfig.yml
